### ISSUE TITLE
It's somehow causing errors tracking with anilist

### ISSUE THREAD

**Issue by BhaturaGuy** [Xposed-Modules-Repo/com.amanoteam.sunny#2]
I get error 404 almost every time when I try to track a new manga or just search or update progress.
But if I turn off the module and force stop and open Tachiyomi it works just fine.

Is this a drawback of the module or just a temporary error?

**Comment by Kartatz** [comment]
hm weird. i don't use anilist, but i will have a look on this soon.

**Comment by Kartatz** [comment]
Can't reproduce this issue.

**Comment by BhaturaGuy** [comment]
> Can't reproduce this issue.

I am pretty sure it is causing the issue. 
Added MAL tracking and its same issue with MAL too.

**Comment by Kartatz** [comment]
Which Tachiyomi client are you using? The official one?

Also, do you see any crash log in the Xposed Manager?

**Comment by BhaturaGuy** [comment]
It happens with every client, Tachiyomi, Tachiyomi -Preview, Aniyomi.

There are no crash logs as it doesn't crash. It does work, downloads manga at fast speed, but creates issues with tracking whenever I try to update chapter number, add new tracking. Or just logging in and out of tracking with Anilist or MAL.

![Screenshot_2023-11-11-15-12-26-62_79aa9bf7c61e266c5f841e42245e214b](https://github.com/Xposed-Modules-Repo/com.amanoteam.sunny/assets/93109835/87829d1a-a9ea-4294-9fda-590674426c8c)
![Screenshot_2023-11-11-15-12-13-79_79aa9bf7c61e266c5f841e42245e214b](https://github.com/Xposed-Modules-Repo/com.amanoteam.sunny/assets/93109835/7192ee10-231d-44eb-802e-d05991347047)
